# Generated by Django 5.2.17 on 2026-09-18 18:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_clarity', models.PositiveSmallIntegerField(help_text='How clearly the instructor explained concepts', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_engagement', models.PositiveSmallIntegerField(help_text='How engaging the session was', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_pace', models.PositiveSmallIntegerField(help_text='Whether the pacing felt right', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='classes.session')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'student'], name='feedback_se_session_0adb7e_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='no_duplicated_feedback'), models.CheckConstraint(condition=models.Q(('rating_clarity__gte', 1), ('rating_clarity__lte', 5)), name='rating_clarity_range'), models.CheckConstraint(condition=models.Q(('rating_engagement__gte', 1), ('rating_engagement__lte', 5)), name='rating_engagement_range'), models.CheckConstraint(condition=models.Q(('rating_pace__gte', 1), ('rating_pace__lte', 5)), name='rating_pace_range')],
            },
        ),
    ]
